# Copyright (C) 2019 Moxa Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

stages:
    - build
    - release

build_aliyun-iot-sdk-c:
    stage: build
    tags:
        - 4530-arm-linux-gnueabihf-5.1
    only:
        - branches
    script:
        - ./setup.sh
        - ./build.sh
        - mkdir -p upload/aliyun-iot-sdk-c
        - cp -r readme README.md upload/aliyun-iot-sdk-c
        - scm upload $CI_COMMIT_REF_NAME

release_aliyun-iot-sdk-c:
    stage: release
    tags:
        - 4530-arm-linux-gnueabihf-5.1
    only:
        - tags
    variables:
        REPOSITORY: "git@github.com:MoxaCorp/ioThinx-4530-aliyun-iot.git"
        BRANCH: "master"
    script:
        - ./setup.sh
        - ./build.sh
        - mkdir -p upload/aliyun-iot-sdk-c
        - cp -r readme README.md upload/aliyun-iot-sdk-c
        - scm upload $CI_COMMIT_REF_NAME
        - git checkout -B $BRANCH
        - git push $REPOSITORY $BRANCH --tags --force
